version: "3.4"

volumes:
  db-data: {}

services:
  api:
    build:
      context: ./
      dockerfile: .docker/Dockerfile.dev
    depends_on:
      - db
    volumes:
      - .:/api
      - /api/node_modules
    environment:
      - PORT
      - DB_CONNECTION
      - DB_HOST=${MONGO_HOST}
      - DB_PORT=${MONGO_PORT}
      - DB_USER=${MONGO_USER}
      - DB_PASSWORD=${MONGO_PASSWORD}
      - DB_DATABASE=${MONGO_DATABASE}
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - CERT_PATH
      - KEY_PATH
      - JWT_SECRET
      - JWT_EXPIRES_IN
      - JWT_ISSUER
      - EMAIL_USER
      - EMAIL_PASS
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_SECURE
      - FIREBASE_TIME_TO_LIVE
      - FIREBASE_PRIORITY
      - FIREBASE_DATABASE_URL
    ports:
      - "${PORT}:${PORT}"
  db:
    image: mongo:3.4-xenial
    restart: always
    environment:
      - MONGO_USER
      - MONGO_PASSWORD
      - MONGO_DATABASE
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
    volumes:
      - db-data:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
  docs:
    build:
      context: .
      dockerfile: .docker/apidoc/Dockerfile
    environment:
      - APIDOC_PORT
    ports:
      - "${APIDOC_PORT}:80"
